#remove next two lines after Firebase 4.6.0 release and before merge
source 'sso://cpdc-internal/spec'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'Firestore_Example' do
  pod 'FirebaseAuth', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'Firestore', :path => '../'

  target 'Firestore_Tests' do
    inherit! :search_paths

    pod 'FirebaseCore', :path => '../../'
    pod 'leveldb-library'

    pod 'OCMock'
    pod 'GoogleTest', :podspec => 'Tests/GoogleTest/GoogleTest.podspec'
  end

  target 'Firestore_IntegrationTests' do
    inherit! :search_paths

    pod 'FirebaseCore', :path => '../../'

    pod 'OCMock'
  end
end

target 'SwiftBuildTest' do
  pod 'Firestore', :path => '../'
end
