# Uncomment the next two lines for pre-release testing
#source 'sso://cpdc-internal/spec'
#source 'https://github.com/CocoaPods/Specs.git'

# The next line is the forcing function for the Firebase pod. The Firebase
# version's subspecs should depend on the component versions in their
# corresponding podspec's.

pod 'Firebase/Core', '5.0.0'

use_frameworks!

target 'Firestore_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseAuth', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseFirestore', :path => '../../'
  pod 'gRPC', :podspec => 'gRPC.podspec'
  pod 'gRPC-C++', :podspec => 'gRPC-C++.podspec'
  pod 'gRPC-Core', :podspec => 'gRPC-Core.podspec'
  pod 'gRPC-ProtoRPC', :podspec => 'gRPC-ProtoRPC.podspec'
  pod 'gRPC-RxLibrary', :podspec => 'gRPC-RxLibrary.podspec'

  target 'Firestore_Tests_iOS' do
    inherit! :search_paths

    pod 'leveldb-library'
    pod 'OCMock'
    pod 'GoogleTest', :podspec => 'Tests/GoogleTest/GoogleTest.podspec'
  end

  target 'Firestore_IntegrationTests_iOS' do
    inherit! :search_paths

    pod 'OCMock'
  end

  target 'Firestore_SwiftTests_iOS' do
    pod 'FirebaseFirestoreSwift', :path => '../../'
  end

  target 'SwiftBuildTest' do
    platform :ios, '8.0'
  end
end
