use_frameworks!
platform :ios, '8.0'

target 'Firestore_Example' do
  pod 'FirebaseCommunity/Core', :path => '../../'
  pod 'Firestore', :path => '../'

  target 'Firestore_Tests' do
    inherit! :search_paths
    pod 'OCMock'
    pod 'leveldb-library'
  end

  target 'Firestore_IntegrationTests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'SwiftBuildTest' do
  pod 'Firestore', :path => '../'
end
