use_frameworks!

target 'FirebaseFunctions_Example' do
  platform :ios, '8.0'

  pod 'FirebaseCore', :path => '../../'
  pod 'GoogleUtilities', :path => '../../'
  pod 'FirebaseFunctions', :path => '../../'

  target 'FirebaseFunctions_Tests' do
    inherit! :search_paths
  end

  target 'FirebaseFunctions_IntegrationTests' do
    inherit! :search_paths
  end
end
