use_frameworks!

target 'FirebaseFunctions_Example' do
  platform :ios, '8.0'

  pod 'FirebaseAuthInterop', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'FirebaseCoreDiagnosticsInterop', :path => '../../'
  pod 'FirebaseFunctions', :path => '../../', :testspecs => ['unit']
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'
  pod 'GoogleUtilities', :path => '../../'

  target 'FirebaseFunctions_Tests' do
    inherit! :search_paths
  end

  target 'FirebaseFunctions_IntegrationTests' do
    inherit! :search_paths
  end
end
