source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../../../../..'
pod 'FirebaseCoreInternal', :path => '../../../../..'
pod 'FirebaseCoreExtension', :path => '../../../../..'
pod 'FirebaseAnalyticsInterop', :path => '../../../../..'
pod 'FirebaseInstallations', :path => '../../../../..'
pod 'FirebaseABTesting', :path => '../../../../..'
pod 'FirebaseInAppMessaging', :path => '../../../../..'

target 'FIAMSwiftUI (iOS)' do
  platform :ios, '15.0'
end
