project 'FrameworkMaker.xcodeproj'

target 'FrameworkMaker_iOS' do
  platform :ios, '7.0'

  pod 'FirebaseAuth', :path => '../Firebase/Auth'
  pod 'FirebaseCore', :path => '../Firebase/Core'
  pod 'FirebaseDatabase', :path => '../Firebase/Database'
  pod 'FirebaseMessaging', :path => '../Firebase/Messaging'
  pod 'FirebaseStorage', :path => '../Firebase/Storage'
end

target 'FrameworkMaker_macOS' do
  platform :osx, '10.10'

  pod 'FirebaseAuth', :path => '../Firebase/Auth'
  pod 'FirebaseCore', :path => '../Firebase/Core'
  pod 'FirebaseDatabase', :path => '../Firebase/Database'
  pod 'FirebaseStorage', :path => '../Firebase/Storage'
end
