use_frameworks!

target 'GDTWatchOSTestAppWatchKitApp' do
  platform :watchos, '6.0'

end

target 'GDTWatchOSTestAppWatchKitExtension' do
  platform :watchos, '6.0'

  # Pods for GDTWatchOSTestAppWatchKitExtension
  pod 'GoogleDataTransport', :path => '../../'

end
