
use_frameworks!
platform :ios, '8.0'

target 'Core_Example' do
  pod 'FirebaseDev/Core', :path => '../'

  target 'Core_Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Auth_Example' do
  pod 'FirebaseDev/Auth', :path => '../'

  target 'Auth_Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Database_Example' do
  pod 'FirebaseDev/Database', :path => '../'

  target 'Database_Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Messaging_Example' do
  pod 'FirebaseDev/Messaging', :path => '../'

  target 'Messaging_Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Storage_Example' do
  pod 'FirebaseDev/Storage', :path => '../'

  target 'Storage_Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
end