
use_frameworks!

target 'Core_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/Core', :path => '../'

  target 'Core_Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Core_Example_macOS' do
  platform :osx, '10.10'

  pod 'FirebaseCommunity/Core', :path => '../'

  target 'Core_Tests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Auth_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/Auth', :path => '../'

  target 'Auth_Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Auth_Example_macOS' do
  platform :osx, '10.10'

  pod 'FirebaseCommunity/Auth', :path => '../'

  target 'Auth_Tests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Database_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/Database', :path => '../'

  target 'Database_Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end

  target 'Database_IntegrationTests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Database_Example_macOS' do
  platform :osx, '10.10'

  pod 'FirebaseCommunity/Database', :path => '../'

  target 'Database_Tests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end

  target 'Database_IntegrationTests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Messaging_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/Messaging', :path => '../'
  pod 'FirebaseInstanceID'

  target 'Messaging_Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Storage_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/Storage', :path => '../'

  target 'Storage_Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end

  target 'Storage_IntegrationTests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Storage_Example_macOS' do
  platform :osx, '10.10'

  pod 'FirebaseCommunity/Storage', :path => '../'

  target 'Storage_Tests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end

  target 'Storage_IntegrationTests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end
