platform :ios, '10.0'

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'SymbolCollisionTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase Pods
    pod 'Firebase', :path => '../'
    pod 'FirebaseABTesting', :path => '../'
    pod 'FirebaseAppDistribution', :path => '../'
    pod 'FirebaseAnalytics'
    pod 'FirebaseAuth', :path => '../'
    pod 'FirebaseCore', :path => '../'
    pod 'FirebaseCoreDiagnostics', :path => '../'
    pod 'FirebaseCrashlytics', :path => '../'
    pod 'FirebaseDatabase', :path => '../'
    pod 'FirebaseDynamicLinks', :path => '../'
    pod 'FirebaseFirestore', :path => '../'
    pod 'FirebaseFunctions', :path => '../'
    pod 'FirebaseInAppMessaging', :path => '../'
    pod 'FirebaseInstallations', :path => '../'
    pod 'FirebaseMessaging', :path => '../'
    pod 'FirebasePerformance', :path => '../'
    pod 'FirebaseRemoteConfig', :path => '../'
    pod 'FirebaseStorage', :path => '../'
    pod 'GoogleUtilitiesComponents', :path => '../'

#    pod 'FirebaseUI'. - requires use_frameworks!

    # Google Pods depending on a Firebase or GDT major version
    pod 'GoogleMLKit'

  # Other Google Pods
#    pod 'ARCore' Conflicts with FirebasePerformance via Clearcut and google-cast-sdk
#    pod 'Blockly' This is a Swift Pod and requires usage of use_frameworks!
    pod 'DigitsMigrationHelper'
    pod 'EarlGrey'
#    pod 'GeoFire' -- requires Firebase/Database 4.0
#    pod 'google-cast-sdk' -- abseil
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleAnalytics'
    pod 'GoogleAppIndexing'
    pod 'GoogleAppUtilities'
    pod 'GoogleAuthUtilities'
    pod 'GoogleConversionTracking'
    pod 'GoogleDataTransport'
    pod 'GoogleIDFASupport'
    pod 'GoogleInterchangeUtilities'
    pod 'GoogleMaps'

#    pod 'GoogleMobileVision' # After Firebase 6.8.0, conflicts with FirebaseML
    pod 'GoogleNetworkingUtilities'
    pod 'GoogleParsingUtilities'
    pod 'GooglePlacePicker'
    pod 'GooglePlaces'
    pod 'GooglePlusUtilities'
    pod 'GoogleSignIn'
    pod 'GoogleSymbolUtilities'
    pod 'GoogleTagManager'
    pod 'GoogleToolboxForMac'
    pod 'GoogleUtilities'
    pod 'GTMAppAuth'
#    pod 'GTMHTTPFetcher' - conflicts with GTMSessionFetcher
    pod 'GTMSessionFetcher'
#    pod 'GVRSDK' -- absl and protobuf duplicates
    pod 'leveldb-library'
#    pod 'MDFTextAccessibility' - conflicts with GVRSDK
    pod 'nanopb'
#    pod 'NearbyMessages' # - conflicts with google-cast-sdk
    pod 'Protobuf'

  # Non-Google Pods

end
