version: 1
metadata:
  authors: "Google"
builder:
  configs:
  - documentation_targets: [FirebaseAILogic, FirebaseAuth, FirebaseAppCheck, FirebaseCore, FirebaseCrashlytics, FirebaseDatabase, FirebaseFirestore, FirebaseFunctions, FirebaseInstallations, FirebaseMessaging, FirebasePerformanceTarget, FirebaseRemoteConfig, FirebaseStorage]
    platform: iOS
