use_frameworks!

target 'Sample' do
  platform :ios, '13.0'

  pod 'FirebaseAnalyticsInterop', :path => '../../../'
  pod 'FirebaseAuthInterop', :path => '../../../'
  pod 'FirebaseCore', :path => '../../../'
  pod 'GoogleUtilities', :path => '../../../'
  pod 'FirebaseMessaging', :path => '../../../'
  pod 'FirebaseInstanceID', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseCoreDiagnosticsInterop', :path => '../../../'
  pod 'GoogleDataTransport', :path => '../../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'

end
