use_frameworks!

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'Sample' do
  platform :ios, '13.0'

  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseMessaging', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseAnalytics'

end
