use_frameworks!

target 'Example_iOS' do
  platform :ios, '8.0'

  pod 'GoogleUtilities', :path => '../../'

  target 'Tests_iOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Example_macOS' do
  platform :osx, '10.11'

  pod 'GoogleUtilities', :path => '../../'

  target 'Tests_macOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

target 'Example_tvOS' do
  platform :tvos, '10.0'

  pod 'GoogleUtilities', :path => '../../'

  target 'Tests_tvOS' do
    inherit! :search_paths
    pod 'OCMock'
  end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name != 'Release'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'GUL_UNSWIZZLING_ENABLED=1', 'GUL_APP_DELEGATE_TESTING=1']
          end
      end
  end
end