# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AuthenticationExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticationExample
  ## Firebase 🔥 Pods
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  
  ### For Email Link/Passwordless Auth
  pod 'FirebaseDynamicLinks'

  ## Pod for Sign in with Google
  pod 'GoogleSignIn'

  ## Pod for Sign in with Facebook
  pod 'FBSDKLoginKit'

  target 'AuthenticationExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticationExampleUITests' do
    # Pods for testing
  end

end
