# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteConfigSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemoteConfigSwiftSample
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'

  target 'RemoteConfigSwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteConfigSwiftSampleUITests' do
    # Pods for testing
  end

end
