# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'RemoteConfigSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemoteConfigSwiftSample
  pod 'FirebaseAnalytics'
  pod 'FirebaseABTesting', :path => '../../..'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseRemoteConfig', :path => '../../../'
  pod 'GoogleDataTransport', :path => '../../..'
  pod 'GoogleUtilities', :path => '../../..'

  target 'RemoteConfigSwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteConfigSwiftSampleUITests' do
    # Pods for testing
  end

end
