use_frameworks! :linkage => :static

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

def shared_pods
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseMessaging', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'GoogleDataTransport'
end

target 'AdvancedSample' do
  platform :ios, '13.0'
  pod 'FirebaseAnalytics'
  shared_pods
end

target 'NotificationServiceExtension' do
  platform :ios, '13.0'
  shared_pods
end

target 'AppClips' do
  platform :ios, '13.0'
  pod 'FirebaseAnalytics'
  shared_pods
end

target 'SampleWatchWatchKitExtension' do
  platform :watchos, '6.0'
  shared_pods
end


