use_frameworks!

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'AuthSwiftUISample' do
  platform :ios, '15.0'

  pod 'FirebaseAuth', :path => '../../../../'
  pod 'FirebaseCore', :path => '../../../../'
  pod 'FirebaseStorage', :path => '../../../../'
  pod 'GoogleMulticastAppDelegate', :path => '../../../../../github/GoogleUtilities/'
end
