# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoapodsIntegrationTest' do
  use_frameworks!

  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInstanceID', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebaseStorage', :path => '../'
  pod 'GoogleUtilities', :path => '../'
end