# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FDLBuilderTestAppObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseInstanceID', :path => '../../../'
  pod 'FirebaseDynamicLinks', :path => '../../../'

end
