source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CocoapodsIntegrationTest' do
  pod 'FirebaseABTesting', :path => '../'
  pod 'FirebaseAppDistribution', :path => '../'
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseCoreDiagnostics', :path => '../'
  pod 'FirebaseCrashlytics', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInstallations', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebasePerformance', :path => '../'
  pod 'FirebaseStorage', :path => '../'
end

# Using the new speed-enhancing features available with CocoaPods 1.7+
# [sudo] gem install cocoapods --pre
install! 'cocoapods',
          :generate_multiple_pod_projects => true,
          :incremental_installation => true
