source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../../../..'
pod 'FirebaseCoreInternal', :path => '../../../..'
pod 'FirebaseInstallations', :path => '../../../..'
pod 'FirebaseABTesting', :path => '../../../..'

target 'FiamDisplaySwiftExample' do
  platform :ios, '13.0'
  pod 'FirebaseInAppMessaging', :path => '../../../..'
end

