source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../../../..'
pod 'FirebaseInstallations', :path => '../../../..'
pod 'FirebaseCoreDiagnostics', :path => '../../../..'
pod 'FirebaseCoreDiagnosticsInterop', :path => '../../../..'
pod 'GoogleDataTransport', :path => '../../../..'
pod 'GoogleDataTransportCCTSupport', :path => '../../../..'
pod 'GoogleUtilities', :path => '../../../..'
pod 'FirebaseABTesting', :path => '../../../..'

target 'FiamDisplaySwiftExample' do
  platform :ios, '9.0'
  pod 'FirebaseInAppMessaging', :path => '../../../..'
  pod 'FirebaseAnalyticsInterop', :path => '../../../..'
end

