use_frameworks!

target 'GDTCCTWatchOSIndependentTestAppWatchKitExtension' do
  platform :watchos, '6.0'

  # Pods for GDTCCTWatchOSIndependentTestAppWatchKitExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'
  pod 'FirebaseAnalyticsInterop', :path => '../../'
  pod 'FirebaseAuthInterop', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'GoogleUtilities', :path => '../../'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'FirebaseCoreDiagnosticsInterop', :path => '../../'
  pod 'FirebaseInstallations', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'

end

target 'GDTCCTServiceExtension' do
  platform :watchos, '6.0'
  
  # Pods for GDTCCTServiceExtension
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'
end


target 'GDTCCTWatchOSCompanionTestAppExtension' do
  platform :watchos, '6.0'
   
  # Pods for GDTCCTWatchOSCompanionTestAppExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'

end
