use_frameworks!

target 'GDTCCTWatchOSIndependentTestAppWatchKitApp' do
  platform :watchos, '6.0'

end

target 'GDTCCTWatchOSIndependentTestAppWatchKitExtension' do
  platform :watchos, '6.0'

  # Pods for GDTCCTWatchOSIndependentTestAppWatchKitExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'

end

target 'GDTCCTWatchOSCompanionTestAppExtension' do
  platform :watchos, '6.0'
   
  # Pods for GDTCCTWatchOSCompanionTestAppExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'

end
