// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// A type that can be initialized from model output.
public protocol ConvertibleFromModelOutput: SendableMetatype {
  /// Creates an instance from content generated by a model.
  ///
  /// Conformance to this protocol is provided by the `@Generable` macro. A manual implementation
  /// may be used to map values onto properties using different names. To manually initialize your
  /// type from model output, decode the values as shown below:
  ///
  /// ```swift
  /// struct Person: ConvertibleFromModelOutput {
  ///     var name: String
  ///     var age: Int
  ///
  ///     init(_ content: ModelOutput) {
  ///         self.name = try content.value(forProperty: "firstName")
  ///         self.age = try content.value(forProperty: "ageInYears")
  ///     }
  /// }
  /// ```
  ///
  /// - Important: If your type also conforms to ``ConvertibleToModelOutput``, it is critical
  /// that this implementation be symmetrical with
  /// ``ConvertibleToModelOutput/modelOutput``.
  ///
  /// - SeeAlso: `@Generable` macro ``Generable(description:)``
  init(_ content: ModelOutput) throws
}
