source 'https://github.com/CocoaPods/Specs.git'

workspace 'FirebaseMessaging'

use_frameworks!

def shared_pods
  pod 'FirebaseCore', :path => '../Core'

  pod 'GoogleToolboxForMac/Logger', '~> 2.1'
  pod 'Protobuf', '~> 3.1'
end

target :FirebaseMessaging_iOS do
  project 'FirebaseMessaging.xcodeproj'
  platform :ios, '8.0'

  shared_pods
end

target :FirebaseMessaging_macOS do
  project 'FirebaseMessaging.xcodeproj'
  platform :osx, '10.10'

  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
