# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'AppCheckCustomProvideApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreInternal', :path => '../../../'
  pod 'FirebaseCoreExtension', :path => '../../../'
  pod 'FirebaseAppCheckInterop', :path => '../../../'
  pod 'FirebaseAppCheck', :path => '../../../'

end
