sdk {
  sdk_name: "Firebase"
  sdk_version: "6.30.0"
}
sdk {
  sdk_name: "FirebaseAnalytics"
  sdk_version: "6.7.0"
}
sdk {
  sdk_name: "FirebaseMLModelInterpreter"
  sdk_version: "0.21.0"
}
sdk {
  sdk_name: "FirebasePerformance"
  sdk_version: "3.2.1"
}
