# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoapodsIntegrationTest' do
  use_frameworks!

  pod 'FirebaseABTesting', :path => '../'
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseCoreDiagnostics', :path => '../'
  pod 'FirebaseCrashlytics', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInstallations', :path => '../'
  pod 'FirebaseInstanceID', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebaseStorage', :path => '../'
  pod 'GoogleDataTransport', :path => '../'
  pod 'GoogleUtilities', :path => '../'
end
