# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteConfigSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseRemoteConfig', :path => '../../../'
  pod 'FirebasePerformance'
  # Pods for RemoteConfigSampleApp

  target 'RemoteConfigSampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
