platform :ios, '13.0'

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'RemoteConfigSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreInternal', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseRemoteConfig', :path => '../../../'
  pod 'FirebaseABTesting', :path => '../../..'
  pod 'FirebaseRemoteConfigInterop', :path => '../../..'

  # Pods for RemoteConfigSampleApp

  target 'RemoteConfigSampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
