use_frameworks!

source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'GDTCCTWatchOSIndependentTestAppWatchKitExtension' do
  platform :watchos, '6.0'

  # Pods for GDTCCTWatchOSIndependentTestAppWatchKitExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'GoogleUtilities', :path => '../../'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'FirebaseInstallations', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'

end

target 'GDTCCTServiceExtension' do
  platform :watchos, '6.0'

  # Pods for GDTCCTServiceExtension
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'
end

target 'GDTCCTWatchOSCompanionTestAppExtension' do
  platform :watchos, '6.0'

  # Pods for GDTCCTWatchOSCompanionTestAppExtension
  pod 'SwiftProtobuf', '~> 1.0'
  pod 'GoogleDataTransport', :path => '../../'

end
