use_frameworks! :linkage => :static

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

def shared_pods
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseAuthExchange', :path => '../../../'
end

target 'AuthExchange' do
  platform :ios, '13.0'
  shared_pods
end
