
use_frameworks!


target 'InAppMessaging_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseCommunity/InAppMessaging', :path => '../..'
  # Lock to the 1.0.9 version of InstanceID since 1.0.10 added a dependency
  # to FirebaseCore
  # pod 'FirebaseInstanceID', '1.0.9'

  #target 'InAppMessaging_Tests_iOS' do
  #  inherit! :search_paths
  #  pod 'FirebaseCommunity/InAppMessaging', :path => '../..'
  #  pod 'OCMock'
  #end
end


#target 'InAppMessaging_Example_Swift_iOS' do
#  platform :ios, '8.0'

#  pod 'FirebaseCommunity/InAppMessaging', :path => '../'
  # Lock to the 1.0.9 version of InstanceID since 1.0.10 added a dependency
  # to FirebaseCore
#  pod 'FirebaseInstanceID', '1.0.9'

  #target 'Messaging_Tests_iOS' do
  #  inherit! :search_paths
  #  pod 'OCMock'
  #end
#end

