use_frameworks! :linkage => :static

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'SampleStandaloneWatchApp Watch App' do
  platform :watchos, '9.0'

  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseMessaging', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'GoogleDataTransport'

end
