# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoapodsIntegrationTest' do
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInstanceID', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebaseStorage', :path => '../'
  pod 'GoogleUtilities', :path => '../'
end

# Using the new speed-enhancing features available with CocoaPods 1.7+
# [sudo] gem install cocoapods --pre
install! 'cocoapods',
          :generate_multiple_pod_projects => true,
          :incremental_installation => true
