target 'ABTQA' do
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'FirebaseCore', :path => '../../..'
  pod 'FirebaseCoreInternal', :path => '../../..'
  pod 'FirebaseCoreExtension', :path => '../../..'
  pod 'FirebaseAnalyticsInterop', :path => '../../..'
  pod 'FirebaseRemoteConfigInterop', :path => '../../..'
  pod 'FirebaseInstallations', :path => '../../..'
  pod 'FirebaseRemoteConfig', :path => '../../..'
  pod 'FirebaseABTesting', :path => '../../..'
end
