use_frameworks!

target 'SampleWatchAppWatchKitExtension' do
  platform :watchos, '6.0'

  pod 'FirebaseCore', :path => '../../'
  pod 'GoogleUtilities', :path => '../../'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'FirebaseInstallations', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'

end

target 'ServiceExtension' do
  platform :watchos, '6.0'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseInstanceID', :path => '../../'
end
