source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'SampleWatchAppWatchKitExtension' do
  platform :watchos, '7.0'

  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'FirebaseInstallations', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'
  pod 'FirebaseRemoteConfig', :path => '../../'
  pod 'FirebaseABTesting', :path => '../../'
  pod 'FirebaseDatabase', :path => '../../'

end

target 'ServiceExtension' do
  platform :watchos, '7.0'
  pod 'FirebaseMessaging', :path => '../../'
end
