source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'SampleWatchAppWatchKitExtension' do
  platform :watchos, '7.0'

  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseCoreInternal', :path => '../../'
  pod 'FirebaseMessaging', :path => '../../'
  pod 'FirebaseCoreExtension', :path => '../../'
  pod 'FirebaseCoreInternal', :path => '../../'
  pod 'FirebaseInstallations', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'
  pod 'FirebaseRemoteConfig', :path => '../../'
  pod 'FirebaseABTesting', :path => '../../'
  pod 'FirebaseDatabase', :path => '../../'
  pod 'FirebaseAppCheckInterop', :path => '../../'
  pod 'FirebaseAuthInterop', :path => '../../'
  pod 'FirebaseRemoteConfigInterop', :path => '../../'

  pod 'Firebase/Messaging', :path => '../../'
  pod 'Firebase/Storage', :path => '../../'
  pod 'Firebase/RemoteConfig', :path => '../../'
  pod 'Firebase/ABTesting', :path => '../../'
  pod 'Firebase/Database', :path => '../../'

end

target 'ServiceExtension' do
  platform :watchos, '7.0'
  pod 'FirebaseMessaging', :path => '../../'
end
