use_frameworks!

target 'SampleWatchAppWatchKitExtension' do
  platform :watchos, '6.0'

  pod 'FirebaseAnalyticsInterop', :path => '../../../../../'
  pod 'FirebaseCore', :path => '../../../../../'
  pod 'GoogleUtilities', :path => '../../../../../'
  pod 'FirebaseMessaging', :path => '../../../../../'
  pod 'FirebaseInstanceID', :path => '../../../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../../../'
  pod 'FirebaseCoreDiagnosticsInterop', :path => '../../../../../'
  pod 'GoogleDataTransport', :path => '../../../../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../../../../'
  pod 'FirebaseInstallations', :path => '../../../../../'

end

target 'ServiceExtension' do
  platform :watchos, '6.0'
  pod 'FirebaseMessaging', :path => '../../../../../'
  pod 'FirebaseInstanceID', :path => '../../../../../'
end
