source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'GoogleNotificationUtilities_Example' do
  pod 'GoogleUtilities/AppDelegateSwizzler', :path => '../../'

  pod 'GoogleNotificationUtilities', :path => '../../'

  target 'GoogleNotificationUtilities_Tests' do
    inherit! :search_paths

    pod 'OCMock'
  end
end

# Set define to turn on GUL_UNSWIZZLING and GUL_APP_DELEGATE_TESTING for the unit tests
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name != 'Release'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'GUL_UNSWIZZLING_ENABLED=1', 'GUL_APP_DELEGATE_TESTING=1']
          end
      end
  end
end
