// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Response message for BidiGenerateContent RPC call.
struct BidiGenerateContentServerMessage: Decodable {
  /// The type of the message.
  enum MessageType: Decodable {
    /// Sent in response to a `BidiGenerateContentSetup` message from the client.
    case setupComplete(BidiGenerateContentSetupComplete)

    /// Content generated by the model in response to client messages.
    case serverContent(BidiGenerateContentServerContent)

    /// Request for the client to execute the `function_calls` and return the
    /// responses with the matching `id`s.
    case toolCall(BidiGenerateContentToolCall)

    /// Notification for the client that a previously issued
    /// `ToolCallMessage` with the specified `id`s should have been not executed
    /// and should be cancelled.
    case toolCallCancellation(BidiGenerateContentToolCallCancellation)

    /// Server will disconnect soon.
    case goAway(GoAway)
  }

  /// The message type.
  let messageType: MessageType

  /// Usage metadata about the response(s).
  let usageMetadata: GenerateContentResponse.UsageMetadata?
}
