# Uncomment the next two lines for pre-release testing on public repo
source 'https://github.com/Firebase/SpecsStaging.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'FirebaseCore', :path => '../..'

target 'FiamDisplaySwiftExample' do
  platform :ios, '8.0'
  pod 'FirebaseInAppMessagingDisplay', :path => '../..'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop', :path => '../..'
end

