source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../..'
pod 'FirebaseInstallations', :path => '../..'

target 'FiamDisplaySwiftExample' do
  platform :ios, '8.0'
  pod 'FirebaseInAppMessagingDisplay', :path => '../..'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop', :path => '../..'
end

