// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation


extension GeminiDataModels {
  /// Logprobs Result
  /// 
  /// Variant:
  /// The log probabilities of the tokens generated by the model. This is useful for understanding the model's confidence in its predictions and for debugging. For example, you can use log probabilities to identify when the model is making a less confident prediction or to explore alternative responses that the model considered. A low log probability can also indicate that the model is "hallucinating" or generating factually incorrect information.
  package struct LogprobsResult: Codable, Sendable, Equatable, Hashable {
    /// Length = total number of decoding steps. The chosen candidates may or may not be in top_candidates.
    /// 
    /// Variant:
    /// A list of the chosen candidate tokens at each decoding step. The length of this list is equal to the total number of decoding steps. Note that the chosen candidate might not be in `top_candidates`.
    package let chosenCandidates: [LogprobsResultCandidate]?
    
    /// Length = total number of decoding steps.
    /// 
    /// Variant:
    /// A list of the top candidate tokens at each decoding step. The length of this list is equal to the total number of decoding steps.
    package let topCandidates: [TopCandidates]?
    
    /// Sum of log probabilities for all tokens.
    /// 
    /// > Important: `logProbabilitySum` is only available in the Gemini Developer API.
    package let logProbabilitySum: Double?
    
    /// Creates a new `LogprobsResult`.
    package init(
      chosenCandidates: [LogprobsResultCandidate]? = nil,
      topCandidates: [TopCandidates]? = nil,
      logProbabilitySum: Double? = nil
    ) {
      self.chosenCandidates = chosenCandidates
      self.topCandidates = topCandidates
      self.logProbabilitySum = logProbabilitySum
    }
    enum CodingKeys: String, CodingKey {
      case chosenCandidates = "chosenCandidates"
      case topCandidates = "topCandidates"
      case logProbabilitySum = "logProbabilitySum"
    }
  }
}