// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// A type that represents a remote multimodal model (like Gemini), with the ability to generate
/// content based on various input types.
public final class TemplateGenerativeModel: Sendable {
  let generativeAIService: GenerativeAIService
  let apiConfig: APIConfig

  /// A list of tools the model may use to generate the next response.
  let tools: [Tool]?

  /// Tool configuration for any `Tool` specified in the request.
  let toolConfig: TemplateToolConfig?

  /// Configuration parameters for sending requests to the backend.
  let requestOptions: RequestOptions

  init(firebaseInfo: FirebaseInfo, apiConfig: APIConfig, tools: [Tool]?,
       toolConfig: TemplateToolConfig?, requestOptions: RequestOptions,
       urlSession: URLSession = GenAIURLSession.default) {
    generativeAIService = GenerativeAIService(
      firebaseInfo: firebaseInfo,
      urlSession: urlSession
    )
    self.apiConfig = apiConfig
    self.tools = tools
    self.toolConfig = toolConfig
    self.requestOptions = requestOptions
  }

  /// Generates content from a prompt template and inputs.
  ///
  /// - Parameters:
  ///   - templateID: The ID of the prompt template to use.
  ///   - inputs: A dictionary of variables to substitute into the template.
  /// - Returns: The content generated by the model.
  /// - Throws: A ``GenerateContentError`` if the request failed.
  public func generateContent(templateID: String,
                              inputs: [String: Any]) async throws -> GenerateContentResponse {
    return try await generateContentWithHistory(history: [], template: templateID, inputs: inputs)
  }

  /// Generates content from a prompt template and inputs, with streaming responses.
  ///
  /// - Parameters:
  ///   - templateID: The ID of the prompt template to use.
  ///   - inputs: A dictionary of variables to substitute into the template.
  /// - Returns: An `AsyncThrowingStream` that yields `GenerateContentResponse` objects.
  /// - Throws: A ``GenerateContentError`` if the request failed.
  @available(macOS 12.0, watchOS 8.0, *)
  public func generateContentStream(templateID: String, inputs: [String: Any]) throws
    -> AsyncThrowingStream<GenerateContentResponse, Error> {
    return try generateContentStreamWithHistory(history: [], template: templateID, inputs: inputs)
  }

  /// Creates a new chat conversation using this model with the provided template, inputs, and
  /// history.
  ///
  /// - Parameters:
  ///   - templateID: The ID of the prompt template to use.
  ///   - inputs: A dictionary of variables to substitute into the template.
  ///   - history: The conversation history to use.
  /// - Returns: A new ``TemplateChatSession`` instance.
  public func startChat(templateID: String,
                        inputs: [String: Any],
                        history: [ModelContent] = []) -> TemplateChatSession {
    return TemplateChatSession(
      model: self,
      templateID: templateID,
      inputs: inputs,
      history: history
    )
  }

  // MARK: - Internal

  func templateGenerateContentRequest(template: String, inputs: [String: Any],
                                      history: [ModelContent],
                                      stream: Bool) throws -> TemplateGenerateContentRequest {
    return try TemplateGenerateContentRequest(
      template: template,
      inputs: inputs.mapValues { try TemplateInput(value: $0) },
      history: history,
      projectID: generativeAIService.firebaseInfo.projectID,
      stream: stream,
      apiConfig: apiConfig,
      options: requestOptions,
      tools: nil, // TODO: Convert `tools` to `TemplateTool` values.
      toolConfig: toolConfig
    )
  }

  /// Generates content from a prompt template, inputs, and history.
  ///
  /// - Parameters:
  ///   - history: The conversation history to use.
  ///   - template: The prompt template to use.
  ///   - inputs: A dictionary of variables to substitute into the template.
  /// - Returns: The content generated by the model.
  /// - Throws: A ``GenerateContentError`` if the request failed.
  func generateContentWithHistory(history: [ModelContent], template: String,
                                  inputs: [String: Any]) async throws -> GenerateContentResponse {
    let request = try templateGenerateContentRequest(
      template: template,
      inputs: inputs,
      history: history,
      stream: false
    )

    return try await generativeAIService.loadRequest(request: request)
  }

  /// Generates a stream of content from a prompt template, inputs, and history.
  ///
  /// - Parameters:
  ///   - history: The conversation history to use.
  ///   - template: The prompt template to use.
  ///   - inputs: A dictionary of variables to substitute into the template.
  /// - Returns: An `AsyncThrowingStream` that yields `GenerateContentResponse` objects.
  /// - Throws: A ``GenerateContentError`` if the request failed.
  @available(macOS 12.0, watchOS 8.0, *)
  func generateContentStreamWithHistory(history: [ModelContent], template: String,
                                        inputs: [String: Any]) throws
    -> AsyncThrowingStream<GenerateContentResponse, Error> {
    let request = try templateGenerateContentRequest(
      template: template,
      inputs: inputs,
      history: history,
      stream: true
    )

    return generativeAIService.loadRequestStream(request: request)
  }
}
