// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import SharedDataModels
package import GoogleAIDataModels
package import AgentPlatformDataModels

// MARK: - GeminiPart

/// A datatype containing media that is part of a multi-part content message.
public struct GeminiPart: Codable, Sendable, Equatable, Hashable {
  /// Result of executing the `executableCode`.
  public var codeExecutionResult: CodeExecutionResult?

  /// Code generated by the model that is meant to be executed.
  public var executableCode: ExecutableCode?

  /// URI based data.
  public var fileData: FileData?

  /// A predicted function call returned from the model.
  public var functionCall: FunctionCall?

  /// The result output of a function call.
  public var functionResponse: FunctionResponse?

  /// Inline media bytes.
  public var inlineData: Blob?

  /// Optional. Media resolution for the input media.
  public var mediaResolution: MediaResolution?

  /// Custom metadata associated with the Part.
  /// - Note: Only supported on GoogleAI backend.
  public var partMetadata: [String: JSONValue]?

  /// Inline text.
  public var text: String?

  /// Optional. Indicates if the part is thought from the model.
  public var thought: Bool?

  /// Optional. An opaque signature for the thought so it can be reused in subsequent requests.
  public var thoughtSignature: String?

  /// Server-side tool call.
  /// - Note: Only supported on GoogleAI backend.
  public var toolCall: ToolCall?

  /// The output from a server-side ToolCall execution.
  /// - Note: Only supported on GoogleAI backend.
  public var toolResponse: ToolResponse?

  /// Optional. Video metadata.
  public var videoMetadata: VideoMetadata?

  public init(
    codeExecutionResult: CodeExecutionResult? = nil,
    executableCode: ExecutableCode? = nil,
    fileData: FileData? = nil,
    functionCall: FunctionCall? = nil,
    functionResponse: FunctionResponse? = nil,
    inlineData: Blob? = nil,
    mediaResolution: MediaResolution? = nil,
    partMetadata: [String: JSONValue]? = nil,
    text: String? = nil,
    thought: Bool? = nil,
    thoughtSignature: String? = nil,
    toolCall: ToolCall? = nil,
    toolResponse: ToolResponse? = nil,
    videoMetadata: VideoMetadata? = nil
  ) {
    self.codeExecutionResult = codeExecutionResult
    self.executableCode = executableCode
    self.fileData = fileData
    self.functionCall = functionCall
    self.functionResponse = functionResponse
    self.inlineData = inlineData
    self.mediaResolution = mediaResolution
    self.partMetadata = partMetadata
    self.text = text
    self.thought = thought
    self.thoughtSignature = thoughtSignature
    self.toolCall = toolCall
    self.toolResponse = toolResponse
    self.videoMetadata = videoMetadata
  }
}

// MARK: - GoogleAI Mappings

extension GeminiPart {
  package func toGoogleAI() -> GoogleAI.Part {
    GoogleAI.Part(
      codeExecutionResult: codeExecutionResult?.toGoogleAI(),
      executableCode: executableCode?.toGoogleAI(),
      fileData: fileData?.toGoogleAI(),
      functionCall: functionCall?.toGoogleAI(),
      functionResponse: functionResponse?.toGoogleAI(),
      inlineData: inlineData?.toGoogleAI(),
      mediaResolution: mediaResolution?.toGoogleAI(),
      partMetadata: partMetadata,
      text: text,
      thought: thought,
      thoughtSignature: thoughtSignature,
      toolCall: toolCall?.toGoogleAI(),
      toolResponse: toolResponse?.toGoogleAI(),
      videoMetadata: videoMetadata?.toGoogleAI()
    )
  }

  package init(fromGoogleAI part: GoogleAI.Part) {
    self.codeExecutionResult = part.codeExecutionResult.map { CodeExecutionResult(fromGoogleAI: $0) }
    self.executableCode = part.executableCode.map { ExecutableCode(fromGoogleAI: $0) }
    self.fileData = part.fileData.map { FileData(fromGoogleAI: $0) }
    self.functionCall = part.functionCall.map { FunctionCall(fromGoogleAI: $0) }
    self.functionResponse = part.functionResponse.map { FunctionResponse(fromGoogleAI: $0) }
    self.inlineData = part.inlineData.map { Blob(fromGoogleAI: $0) }
    self.mediaResolution = part.mediaResolution.map { MediaResolution(fromGoogleAI: $0) }
    self.partMetadata = part.partMetadata
    self.text = part.text
    self.thought = part.thought
    self.thoughtSignature = part.thoughtSignature
    self.toolCall = part.toolCall.map { ToolCall(fromGoogleAI: $0) }
    self.toolResponse = part.toolResponse.map { ToolResponse(fromGoogleAI: $0) }
    self.videoMetadata = part.videoMetadata.map { VideoMetadata(fromGoogleAI: $0) }
  }
}

// MARK: - AgentPlatform Mappings

extension GeminiPart {
  package func toAgentPlatform() -> AgentPlatform.Part {
    AgentPlatform.Part(
      codeExecutionResult: codeExecutionResult?.toAgentPlatform(),
      executableCode: executableCode?.toAgentPlatform(),
      fileData: fileData?.toAgentPlatform(),
      functionCall: functionCall?.toAgentPlatform(),
      functionResponse: functionResponse?.toAgentPlatform(),
      inlineData: inlineData?.toAgentPlatform(),
      mediaResolution: mediaResolution.map { AgentPlatform.PartMediaResolution(level: $0.toAgentPlatform()) },
      text: text,
      thought: thought,
      thoughtSignature: thoughtSignature,
      videoMetadata: videoMetadata?.toAgentPlatform()
    )
  }

  package init(fromAgentPlatform part: AgentPlatform.Part) {
    self.codeExecutionResult = part.codeExecutionResult.map { CodeExecutionResult(fromAgentPlatform: $0) }
    self.executableCode = part.executableCode.map { ExecutableCode(fromAgentPlatform: $0) }
    self.fileData = part.fileData.map { FileData(fromAgentPlatform: $0) }
    self.functionCall = part.functionCall.map { FunctionCall(fromAgentPlatform: $0) }
    self.functionResponse = part.functionResponse.map { FunctionResponse(fromAgentPlatform: $0) }
    self.inlineData = part.inlineData.map { Blob(fromAgentPlatform: $0) }
    self.mediaResolution = part.mediaResolution?.level.map { MediaResolution(fromAgentPlatform: $0) }
    self.partMetadata = nil
    self.text = part.text
    self.thought = part.thought
    self.thoughtSignature = part.thoughtSignature
    self.toolCall = nil
    self.toolResponse = nil
    self.videoMetadata = part.videoMetadata.map { VideoMetadata(fromAgentPlatform: $0) }
  }
}
