# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tvOSSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tvOSSample
  pod 'FirebaseCommunity/Core', :path => '../../'
  pod 'FirebaseCommunity/Storage', :path => '../../'

end
