
target 'tvOSSample' do
  platform :tvos, '11.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tvOSSample
  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../'
  pod 'FirebaseCoreDiagnosticsInterop', :path => '../../'
  pod 'FirebaseAuth', :path => '../../'
  pod 'FirebaseAuthInterop', :path => '../../'
  pod 'FirebaseDatabase', :path => '../../'
  pod 'FirebaseStorage', :path => '../../'
  pod 'GoogleDataTransport', :path => '../../'
  pod 'GoogleDataTransportCCTSupport', :path => '../../'

end
