source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ClientApp-CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClientApp-CocoaPods
  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseInstallations', :path => '../'
  pod 'FirebaseAnalytics' # Binary pods don't work with `:path`.
  pod 'FirebaseAnalyticsOnDeviceConversion', :path => '../'
  pod 'FirebaseAnalyticsSwift', :path => '../'
  pod 'FirebaseABTesting', :path => '../'
  pod 'FirebaseAppCheck', :path => '../'
  pod 'FirebaseRemoteConfig', :path => '../'
  pod 'FirebaseRemoteConfigSwift', :path => '../'
  pod 'FirebaseAppDistribution', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseCrashlytics', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDatabaseSwift', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFirestoreSwift', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInAppMessagingSwift', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebasePerformance', :path => '../'
  pod 'FirebaseStorage', :path => '../'
  pod 'FirebaseMLModelDownloader', :path => '../'
  pod 'Firebase', :path => '../'

end
