source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'ClientApp-CocoaPods' do
  platform :ios, '11.0'

  use_frameworks!

  pod 'FirebaseCore', :path => '../'
  pod 'FirebaseInstallations', :path => '../'
  pod 'FirebaseAnalytics' # Binary pods don't work with `:path`.
  pod 'FirebaseAnalyticsOnDeviceConversion', :path => '../'
  pod 'FirebaseABTesting', :path => '../'
  pod 'FirebaseAppCheck', :path => '../'
  pod 'FirebaseRemoteConfig', :path => '../'
  pod 'FirebaseRemoteConfigSwift', :path => '../'
  pod 'FirebaseAppDistribution', :path => '../'
  pod 'FirebaseAuth', :path => '../'
  pod 'FirebaseCrashlytics', :path => '../'
  pod 'FirebaseDatabase', :path => '../'
  pod 'FirebaseDatabaseSwift', :path => '../'
  pod 'FirebaseDynamicLinks', :path => '../'
  pod 'FirebaseFirestore', :path => '../'
  pod 'FirebaseFirestoreSwift', :path => '../'
  pod 'FirebaseFunctions', :path => '../'
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseMessaging', :path => '../'
  pod 'FirebasePerformance', :path => '../'
  pod 'FirebaseStorage', :path => '../'
  pod 'FirebaseMLModelDownloader', :path => '../'
  pod 'Firebase', :path => '../'
end

target 'ClientApp-CocoaPods-iOS13' do
  platform :ios, '13.0'

  use_frameworks!

  pod 'FirebaseAnalytics' # Binary pods don't work with `:path`.
  pod 'FirebaseAnalyticsSwift', :path => '../' # Requires iOS 13.0+
  pod 'FirebaseInAppMessaging', :path => '../'
  pod 'FirebaseInAppMessagingSwift', :path => '../' # Requires iOS 13.0+

end
