# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'FirebasePodTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase', :path => '../../../'
  pod 'FirebaseABTesting', :path => '../../../'
  pod 'FirebaseAppDistribution', :path => '../../../'
  pod 'FirebaseAuth', :path => '../../../'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseCrashlytics', :path => '../../../'
  pod 'FirebaseDatabase', :path => '../../../'
  pod 'FirebaseDynamicLinks', :path => '../../../'
  pod 'FirebaseFirestore', :path => '../../../'
  pod 'FirebaseFunctions', :path => '../../../'
  pod 'FirebaseInAppMessaging', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseInstanceID', :path => '../../../'
  pod 'FirebaseMessaging', :path => '../../../'
  pod 'FirebasePerformance', :path => '../../../'
  pod 'FirebaseRemoteConfig', :path => '../../../'
  pod 'FirebaseStorage', :path => '../../../'

  # Get dependent pods from the repo also
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'GoogleDataTransport', :path => '../../../'

  pod 'FirebaseAnalytics' # Analytics is not open source
end
