source 'https://github.com/CocoaPods/Specs.git'

workspace 'FirebaseDatabase'

use_frameworks!

def shared_pods
  pod 'FirebaseCore', :path => '../Core'
  
  pod 'leveldb-library'
end

target :FirebaseDatabase_iOS do
  project 'FirebaseDatabase.xcodeproj'
  platform :ios, '8.0'

  shared_pods
end

target :FirebaseDatabase_macOS do
  project 'FirebaseDatabase.xcodeproj'
  platform :osx, '10.10'

  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
