# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
#   "iPhone 4s",
   "iPhone 6 Plus",
   "iPhone 5s",
   "iPhone 7",
   "iPad Pro (12.9 inch)",
#   "iPad Pro (9.7 inch)",
#   "Apple TV 1080p"
 ])


languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "InAppMessaging_Example_iOS_Swift"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

workspace "InAppMessaging-Example-iOS.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
