// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT. This file is generated by GeminiLanguageModel/scripts/typegen;
// see its README.md for how to regenerate it.

import Foundation

/// A piece of evidence that supports a claim made by the model. This is used to show a citation for
/// a claim made by the model. When grounding is enabled, the model returns a `GroundingChunk` that
/// contains a reference to the source of the information.
package struct GroundingChunk: Codable, Sendable, Equatable, Hashable, Buildable {
  /// A grounding chunk from an image search result. See the `Image` message for details.
  package var image: ImageChunk?

  /// A grounding chunk from Google Maps. See the `Maps` message for details.
  package var maps: MapsChunk?

  /// A grounding chunk from a web page, typically from Google Search. See the `Web` message for
  /// details.
  package var web: WebChunk?

  /// Initializes a new `GroundingChunk`.
  package init() {}

  enum CodingKeys: String, CodingKey {
    case image
    case maps
    case web
  }
}
