# This Podfile and FrameworkMaker.xcodeproj is only here to access the
# ProtoCompiler plugin.

# Source Firebase dependencies from a fast mirror for CocoaPods master
source 'https://github.com/paulb777/FirebaseDependencySpecs'

project 'FrameworkMaker.xcodeproj'

target 'FrameworkMaker_iOS' do
  platform :ios, '7.0'

  # This should be versioned along with 'gRPC-ProtoRPC' in Firestore.podspec
  pod '!ProtoCompiler-gRPCPlugin'
end
