source 'https://github.com/CocoaPods/Specs.git'

workspace 'FirebaseStorage'

use_frameworks!

def shared_pods
  pod 'FirebaseCore', :path => '../Core'

  pod 'GTMSessionFetcher/Core', '~> 1.1'
end

target :FirebaseStorage_iOS do
  project 'FirebaseStorage.xcodeproj'
  platform :ios, '8.0'

  shared_pods
end

target :FirebaseStorage_macOS do
  project 'FirebaseStorage.xcodeproj'
  platform :osx, '10.10'

  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
