# Uncomment the next two lines for pre-release testing on internal repo
#source 'sso://cpdc-internal/firebase'
#source 'https://cdn.cocoapods.org/'

source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

target 'AuthSample' do
  platform :ios, '14.0'  
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreDiagnostics', :path => '../../../'
  pod 'FirebaseCoreInternal', :path => '../../../'
  pod 'FirebaseAuth', :path => '../../../', :testspecs => ['unit']
  pod 'FirebaseInstallations', :path => '../../..'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn', '~> 6'
  pod 'GTMSessionFetcher/Core'

  target 'Auth_ApiTests' do
    inherit! :search_paths
    # `HeartbeatLoggingTestUtils` is unpublished.
    pod 'HeartbeatLoggingTestUtils', :path => '../../../'
  end

  target 'SwiftApiTests' do
    inherit! :search_paths
  end

  target 'Auth_E2eTests' do
    inherit! :search_paths
    pod 'EarlGrey'
  end
end
