source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'FIRAppCheckTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIRAppCheckTestApp
  pod 'FirebaseAppCheck', :path => '../../../'

  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseStorage', :path => '../../../'
  pod 'RecaptchaEnterprise'

  # Use local AppCheckCore if the environment variable is set
  if ENV['FIREBASE_APP_CHECK_LOCAL_PATH']
    pod 'AppCheckCore', :path => ENV['FIREBASE_APP_CHECK_LOCAL_PATH']
  end
end
