
use_frameworks!
platform :ios, '8.0'

target 'Sample' do
  pod 'FirebaseDev/Auth', :path => '../'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  # Lock to the 1.0.9 version of InstanceID since 1.0.10 added a dependency
  # to FirebaseCore
  pod 'FirebaseInstanceID', '1.0.9'
end

target 'SwiftSample' do
  pod 'FirebaseDev/Auth', :path => '../'
  pod 'GoogleSignIn'
  pod 'FirebaseInstanceID', '1.0.9'
end
