use_frameworks!

# Uncomment the next two lines for pre-release testing on public repo
source 'https://github.com/Firebase/SpecsStaging.git'
source 'https://github.com/CocoaPods/Specs.git'

# Remove version from FirebaseAnalytics after 6.0 goes public.
pod 'FirebaseAnalytics', '6.0.0-pre'
pod 'FirebaseCore', :path => '../..'

target 'InAppMessaging_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseInAppMessagingDisplay', :path => '../..'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop',  :path => '../..'
  pod 'FirebaseDynamicLinks',  :path => '../..'
  pod 'FirebaseInstanceID',  :path => '../..'
end

target 'InAppMessaging_Tests_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseInstanceID',  :path => '../..'
  pod 'FirebaseAnalyticsInterop',  :path => '../..'
  pod 'OCMock'
end
