use_frameworks!

source 'https://cdn.cocoapods.org/'

pod 'FirebaseAnalytics'
pod 'FirebaseCore', :path => '../..'
pod 'FirebaseInstanceID',  :path => '../..'
pod 'FirebaseInstallations', :path => '../..'
pod 'FirebaseCoreDiagnostics', :path => '../..'
pod 'FirebaseCoreDiagnosticsInterop', :path => '../..'
pod 'GoogleDataTransport', :path => '../..'
pod 'GoogleDataTransportCCTSupport', :path => '../..'
pod 'GoogleUtilities', :path => '../..'

target 'InAppMessaging_Example_iOS' do
  platform :ios, '8.0'

  pod 'FirebaseInAppMessagingDisplay', :path => '../..'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop',  :path => '../..'
  pod 'FirebaseDynamicLinks',  :path => '../..'

end

target 'InAppMessaging_Tests_iOS' do
  platform :ios, '8.0'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop',  :path => '../..'
  pod 'OCMock', '~> 3.4.0'
end
