source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../..'
pod 'FirebaseCoreDiagnostics', :path => '../..'
pod 'FirebaseCoreDiagnosticsInterop', :path => '../..'
pod 'GoogleDataTransport', :path => '../..'
pod 'GoogleDataTransportCCTSupport', :path => '../..'
pod 'GoogleUtilities', :path => '../..'

target 'FiamDisplaySwiftExample' do
  platform :ios, '8.0'
  pod 'FirebaseInAppMessaging', :path => '../..'
  pod 'FirebaseAnalyticsInterop', :path => '../..'
end

