# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'SwiftUISample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore', :path => '../../../'
  pod 'FirebaseCoreInternal', :path => '../../../'
  pod 'FirebaseInstallations', :path => '../../../'
  pod 'FirebaseRemoteConfig', :path => '../../../'
  pod 'FirebaseSharedSwift', :path => '../../..'
  pod 'FirebaseABTesting', :path => '../../..'

end
