platform :ios, '10.0'
use_frameworks!

pod 'FirebaseMLModelDownloader', :path => '../../../'
pod 'TensorFlowLiteSwift'

target 'MLDownloaderTestApp' do
    target 'MLDownloaderTestAppTests' do
    end

    target 'MLDownloaderTestAppUITests' do
    end

end
