platform :ios, '13.0'
use_frameworks!

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

pod 'FirebaseCore', :path => '../../../'
pod 'FirebaseCoreInternal', :path => '../../../'
pod 'FirebaseMLModelDownloader', :path => '../../../'
pod 'TensorFlowLiteSwift'

target 'MLDownloaderTestApp' do
    target 'MLDownloaderTestAppTests' do
    end

    target 'MLDownloaderTestAppUITests' do
    end

end
