name: infra.danger

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  danger:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: macos-15
    permissions:
      issues: write
      pull-requests: write
      contents: read # Required to read the Dangerfile
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false

    - name: Generate GitHub App Token
      id: generate-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ secrets.DANGER_APP_ID }}
        private-key: ${{ secrets.DANGER_APP_PRIVATE_KEY }}
        repositories: ${{ github.event.repository.name }}
        permission-pull-requests: write
        permission-issues: write
        permission-contents: read

    - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
    - name: Setup Bundler
      run: scripts/setup_bundler.sh

    - name: Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token }}
      run:  '[ ! -z "$DANGER_GITHUB_API_TOKEN" ] && bundle exec danger || echo "Skipping Danger for External Contributor"'
