name: infra.ftl.nightly

permissions:
  contents: read

on:
  schedule:
    # Every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
  pull_request:
    paths:
    - '.github/workflows/infra.ftl.nightly.yml'
    - 'Gemfile*'

env:
  FIREBASECI_USE_LATEST_GOOGLEAPPMEASUREMENT: 1

jobs:
  ftl_test:
    if: github.repository == 'Firebase/firebase-ios-sdk'
    runs-on: macos-15
    name: ${{ matrix.product }}
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - product: Messaging
            setup_command: scripts/setup_quickstart.sh messaging
            plist_src_path: scripts/gha-encrypted/qs-messaging.plist.gpg
            plist_dst_path: quickstart-ios/messaging/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh Messaging
          - product: Storage
            setup_command: scripts/setup_quickstart.sh storage
            plist_src_path: scripts/gha-encrypted/qs-storage.plist.gpg
            plist_dst_path: quickstart-ios/storage/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh Storage swift
          - product: Crashlytics
            setup_command: scripts/setup_quickstart.sh crashlytics
            plist_src_path: scripts/gha-encrypted/qs-crashlytics.plist.gpg
            plist_dst_path: quickstart-ios/crashlytics/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh Crashlytics swift
          - product: ABTesting
            setup_command: scripts/setup_quickstart.sh abtesting
            plist_src_path: scripts/gha-encrypted/qs-abtesting.plist.gpg
            plist_dst_path: quickstart-ios/abtesting/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh ABTesting
          - product: Performance
            setup_command: scripts/setup_quickstart.sh performance
            plist_src_path: scripts/gha-encrypted/qs-performance.plist.gpg
            plist_dst_path: quickstart-ios/performance/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh Performance swift
          - product: Installations
            setup_command: scripts/setup_quickstart.sh installations
            plist_src_path: scripts/gha-encrypted/Installations/GoogleService-Info.plist.gpg
            plist_dst_path: quickstart-ios/installations/GoogleService-Info.plist
            build_command: scripts/test_quickstart_ftl.sh Installations
          # TODO(ncooke3): Get these samples building.
          # - product: Authentication
          #   setup_command: scripts/setup_quickstart.sh authentication
          #   plist_src_path: scripts/gha-encrypted/qs-authentication.plist.gpg
          #   plist_dst_path: quickstart-ios/authentication/GoogleService-Info.plist
          #   build_command: scripts/test_quickstart_ftl.sh Authentication
          #   This is probably dated: sed -i '' 's/REVERSED_CLIENT_ID/com.googleusercontent.apps.1025801074639-6p6ebi8amuklcjrto20gvpe295smm8u6/' quickstart-ios/functions/LegacyFunctionsQuickstart/FunctionsExample/Info.plist
          # - product: Functions
          #   setup_command: scripts/setup_quickstart.sh functions
          #   plist_src_path: scripts/gha-encrypted/qs-functions.plist.gpg
          #   plist_dst_path: quickstart-ios/functions/GoogleService-Info.plist
          #   build_command: scripts/test_quickstart_ftl.sh Functions
          # - product: RemoteConfig
          #   setup_command: scripts/setup_quickstart.sh remoteConfig
          #   plist_src_path: scripts/gha-encrypted/qs-functions.plist.gpg
          #   plist_dst_path: quickstart-ios/functions/GoogleService-Info.plist
          #   build_command: scripts/test_quickstart_ftl.sh RemoteConfig
    uses: ./.github/workflows/_quickstart.yml
    with:
      product: ${{ matrix.product }}
      setup_command: ${{ matrix.setup_command }}
      plist_src_path: ${{ matrix.plist_src_path }}
      plist_dst_path: ${{ matrix.plist_dst_path }}
      # The ftl_test job in this workflow explicitly runs a Firebase Test Lab action
      # after the quickstart build, so the `_quickstart.yml` workflow should
      # only build and not run tests.
      run_tests: false
    secrets:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    - id: ftl_test
      uses: FirebaseExtended/github-actions/firebase-test-lab@57091ac526b308ae005c6d6d59aab83d5ab2aa71 # v1.5.0
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIALS }}
        testapp_dir: quickstart-ios/build-for-testing
        test_type: "xctest"
