name: sdk.ai

on:
  pull_request:
    paths:
    - 'FirebaseAI**'
    - '.github/workflows/sdk.ai.yml'
    - '.github/workflows/_spm.yml'
    - '.github/workflows/_cocoapods.yml'
    - 'scripts/build.sh'
    - 'scripts/quickstart_build_spm.sh'
    - 'scripts/update_firebase_spm_dependency.sh'
    - 'Gemfile*'
    # Do not run for documentation-only PRs.
    - '!**.md'
  schedule:
    # Run every day at 12am (PDT) / 3am (EDT) - cron uses UTC times
    - cron:  '0 7 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  # Needed for actions/checkout

jobs:
  spm:
    strategy:
      matrix:
        target: [FirebaseAILogicUnit, FirebaseAIUnit]
    uses: ./.github/workflows/_spm.yml
    with:
      target: ${{  matrix.target }}
      test_xcode27: true
      setup_command: scripts/update_vertexai_responses.sh
      env_vars: '{"FIREBASE_APP_CHECK_BRANCH": "main"}'

  testapp-integration:
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    strategy:
      matrix:
        include:
          - os: macos-15
            target: iOS
            xcode: Xcode_26.2
            test_filter_arg: --exclude IntegrationTests-SPM/LiveSessionTests
            log_prefix: xcodebuild
          - os: macos-15
            target: iOS
            xcode: Xcode_26.2
            test_filter_arg: --filter IntegrationTests-SPM/LiveSessionTests
            log_prefix: xcodebuild-live
          - os: macos-26
            target: iOS
            # TODO: Bump to 26.4 when "Unable to find a destination matching the provided destination specifier" is resolved.
            xcode: Xcode_26.2
            test_filter_arg: --exclude IntegrationTests-SPM/LiveSessionTests
            log_prefix: xcodebuild
          - os: macos-26
            target: iOS
            # TODO: Bump to 26.4 when "Unable to find a destination matching the provided destination specifier" is resolved.
            xcode: Xcode_26.2
            test_filter_arg: --filter IntegrationTests-SPM/LiveSessionTests
            log_prefix: xcodebuild-live
          - os: xcode-27
            target: iOS
            xcode: Xcode_27.0
            test_filter_arg: --exclude IntegrationTests-SPM/LiveSessionTests
            log_prefix: xcodebuild
    runs-on: ${{ matrix.os }}
    needs: spm
    env:
      TEST_RUNNER_FIRAAppCheckDebugToken: ${{ secrets.VERTEXAI_INTEGRATION_FAC_DEBUG_TOKEN }}
      TEST_RUNNER_VTXIntegrationImagen: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      FIREBASECI_USE_LATEST_GOOGLEAPPMEASUREMENT: 1
      secrets_passphrase: ${{ secrets.GHASecretsGPGPassphrase1 }}
      FIREBASE_APP_CHECK_BRANCH: main
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: .build
        key: ${{ needs.spm.outputs.cache_key }}
    - name: Run integration tests
      run: scripts/repo.sh tests run --secrets ./scripts/secrets/AI.json --platforms ${{ matrix.target }} --xcode ${{ matrix.xcode }} ${{ matrix.test_filter_arg }} AI
    - name: Upload xcodebuild logs
      if: failure()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ matrix.log_prefix }}-${{ matrix.target }}-${{ matrix.os }}-${{ matrix.xcode }}.log
        path: xcodebuild-*.log
        retention-days: 2

  pod_lib_lint:
    strategy:
      matrix:
        product: [FirebaseAILogic, FirebaseAI]
    uses: ./.github/workflows/_cocoapods.yml
    with:
      product: ${{  matrix.product }}
      test_xcode27: true
      supports_swift6: true
      setup_command: scripts/update_vertexai_responses.sh

  quickstart:
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    strategy:
      matrix:
        include:
          - os: macos-15
            xcode: Xcode_26.2
          # TODO: Bump to 26.4 when "Unable to find a destination matching the provided destination specifier" is resolved.
          - os: macos-26
            xcode: Xcode_26.2
          - os: xcode-27
            xcode: Xcode_27.0
    runs-on: ${{ matrix.os }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name || 'main' }}
      FIREBASE_APP_CHECK_BRANCH: main
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false
    - name: Xcode
      run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - name: Install simulators in case they are missing.
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      with:
        timeout_minutes: 15
        max_attempts: 5
        retry_wait_seconds: 120
        continue_on_error: true
        command: xcodebuild -downloadPlatform iOS
    - name: Build Quickstart
      run: scripts/quickstart_build_spm.sh FirebaseAI
