name: sdk.appdistribution

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'FirebaseAppDistribution**'
    - '.github/workflows/sdk.appdistribution.yml'
    - '.github/workflows/_spm.yml'
  schedule:
    # Run every day at 2am (PDT) / 5am (EDT) - cron uses UTC times
    - cron: '0 9 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  spm:
    strategy:
      matrix:
        target: [AppDistributionUnit, AppDistributionUnitSwift]
    uses: ./.github/workflows/_spm.yml
    with:
      target: ${{ matrix.target }}
      platforms: iOS


