name: 'Generate NOTICES'
description: 'Generate a NOTICES containning SDK licenses.'
inputs:
  pods:
    description: 'Targeted Pods for licences'
    required: true
  sources:
    description: 'Sources of PodSpecs'
    required: true
    default: 'https://cdn.cocoapods.org'
  min-ios-version:
    description: 'The minimum version of iOS'
    required: true
    default: '10.0'
  search-local-pod-version:
    description: 'Add pod version from local spec repo'
    required: true
    default: false
    type: boolean
  notices-path:
    description: 'Path of Notices file containing all licences.'
    required: true
outputs:
  notices_contents:
    description: 'contents of notices'
runs:
  using: 'composite'
  steps:
  - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1
    with:
      ruby-version: "2.7"
  - name: Generate a NOTICES file
    env:
      PODS: ${{ inputs.pods }}
      SOURCES: ${{ inputs.sources }}
      MIN_IOS_VERSION: ${{ inputs.min-ios-version }}
      SEARCH_LOCAL_POD_VERSION: ${{ inputs.search-local-pod-version }}
      NOTICES_PATH: ${{ inputs.notices-path }}
    run: |
      cd "${{ github.action_path }}"
      bundle install
      if [ "$SEARCH_LOCAL_POD_VERSION" == "true" ]; then
        ruby app.rb --pods "$PODS" --sources "$SOURCES" --min_ios_version "$MIN_IOS_VERSION" --search_local_pod_version --notices_path "$NOTICES_PATH"
      else
        ruby app.rb --pods "$PODS" --sources "$SOURCES" --min_ios_version "$MIN_IOS_VERSION" --notices_path "$NOTICES_PATH"
      fi
    shell: bash
  - name: Upload artifacts
    uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
    with:
      name: notices
      path: ${{ inputs.notices-path }}
